server.port=9090
spring.application.name=api-gateway

# Eureka client settings for registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enable Discovery Client integration with Gateway routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Keep registry client running immediately
eureka.instance.prefer-ip-address=true
