server.port=8082
spring.application.name=greet-service

# Eureka client settings for registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Ensure immediate registry registration (handy for testing)
eureka.instance.prefer-ip-address=true
